### ISSUE TITLE
Exact versions: why

### ISSUE THREAD

**Issue by MatissJanis** [wallet77/qualscan#27] opened 2021-02-08 17:36 UTC
Hey!

Amazing work on the package. Just wanted to check: why is the preferred approach to use exact versions?

Personally I've never seen this being a recommendation. I've actually seen the opposite - this being disapproved. So I'm genuinely curious.

Source: https://github.com/wallet77/qualscan/blob/main/doc/dependencies-exact-version.md

**Comment by wallet77** [comment] 2021-02-09 12:19
Hi @MatissJanis ,

Thank you for your support.
This task was done to avoid some potential strange behavior when you run your app on different servers. Or when you build different images for example.
Range versions can lead to unexpected behavior because you can't guarantee which version will be shipped with your code.
With exact version is more predictable and rollback is easier.
But it has some drawbacks too.

A very good article on this subject: https://docs.renovatebot.com/dependency-pinning/
As you can see, it concludes that sometimes we should use range versions and sometimes exact versions.
It's not really easy to choose :)
This is why everything in Qualscan is customizable, you can ignore this task (exact version) or increase the threshold.

But, in this tool, keep in mind that all tasks and all default values for threshold are a little bit "subjective" because it was my own decision.
And this is why I'm very happy to hear your feedback, we should create a community around this tool to discuss all together what we want to check and what default value for each threshold makes sense.

I will probably close this issue but I will open a new ticket in the roadmap to, at least, brainstorm about this topic if you agree.

**Comment by MatissJanis** [comment] 2021-02-09 12:26
Great write-up. However, IMHO a better approach than defining exact versions is to use a lockfile. I know it has some drawbacks in NPM.. But alas `npm ci` solves those. And other package managers such as `yarn` performs pure lockfile installations by-default.

**Comment by wallet77** [comment] 2021-02-09 12:35
Yes, you are right, lockfile is the real savior here :)
I did this task to ensure that even a project without lockfile has only exact versions.

Maybe we can optimize the tool to detect if a lockfile exists, if not we can run the current code.

**Comment by MatissJanis** [comment] 2021-02-09 12:48
That sounds like the ideal solution :)

**Closed as completed** 2021-02-09 18:56 UTC
